### ISSUE TITLE
service workers go to sleep

### ISSUE THREAD

**Issue by s-cork** [anvilistas/anvil-labs#104]
this is a bit of pain - my prototypes have been short
but if I leave the app open for a while then worker seems to go to sleep
and it wakes up when its needed

The problem here is when it wakes up it doesn't remember the information it was told
i.e. it forgets which script it was running
(it also forgets its app origin)

I think we need to store these in localStorage/indexedDB
i.e. the currently active python module and the current appOrigin

Either that or when it wakes up it fires a message over to the browser
~the browser then replies with the information requested i.e. - oh which module were you running?~
~and what's your appOrigin?~
_We can't do the above since the client might not be connected_

Since the client might not be connected - we'll need to store the script, and all the requested imports in browser indexedDB
We can't trust that when we wake up we'll have access to the python modules again

**Comment by rhurlbatt** [comment]
Yeah that is problematic.

For our use case this is likely to happen frequently. It may be 10 hours or so between the sync tag being registered and the listener firing when connection is re-established (if I have my terminology right).
We can't do the above since the client might not be connected

> We can't do the above since the client might not be connected
Agreed. If the device powers off we could see this happen.
