### ISSUE TITLE
Enable `kompot.call` to compile results from multiple server functions

### ISSUE THREAD

**Issue by hugetim** [anvilistas/anvil-labs#64]
What if you could pass multiple server function calls to the kompot `call` function, retrieving multiple return values with a single round trip to the server? I think this could facilitate cleaner, more flexible code that is easier to read, without sacrificing performance.

The `call` function could check if the first argument is a list (or tuple).[1] If so, it would treat each of the items as a separate server function call, returning a list of their respective return values. For example, you could have a simple plural `call` like this:

`name, books = kompot.call(['get_user_name', 'get_user_books'])`

Or, to pass arguments to the server functions, you could specify a list of tuples like this:
`name, books = kompot.call([('get_user_name', user_id), ('get_user_books', user_id)])`

Currently, to accomplish the same thing with a single server round trip, you'd need to write a new server function that explicitly combines the two.

[1] It may also be nice to be able to specify a dictionary with server call specifications as the values, in which case `call` would return a dictionary with the respective return values indexed by the same keys as the input dictionary.

**Comment by s-cork** [comment]
I don't think that something we can do in this layer. 

We could implement the API but since we wrap anvil.server.call, the code to make that work would be to do two anvil.server.call's, negating any performance improvements. 

The layer required to implement that would be a level deeper where anvil is searching for which server functions to call. We don't have access to that layer. 


Maybe we could call out to a generic server function like

```
@anvil.server.call
def kompot_redirect(...):
   ...
```

and if we encountered a list of strings we could redirect to this server function. This would move multiple server calls to the server. But doing a server call on the server is similar to the client - it's just a bit faster. 

What about args and kws in this idea?

**Comment by hugetim** [comment]
I was thinking the generic server function would be able to call the functions directly (that is, not via anvil.server.call). And that the kompot `@callable` decorator could register them with the server module so that it would be able to do that (similar to how the `navigation` module works).

For args and kwargs, I guess I don't have a way in mind to do kwargs. My idea to pass server function specifications as tuples only works for positional arguments. Hmm, maybe instead of tuples, you could define a portable class (as part of kompot) called `s_fn` or something, which could be initialized with args and kwargs that could then be passed on. So the sample code could be something like:
```python
name, books = kompot.call([
    s_fn('get_user_name', user_id=user_id),
    s_fn('get_user_books', user_id=user_id),
])
```

I'm probably still missing things, though.

**Comment by s-cork** [comment]
Ah interesting I hadn't thought of having our own registry of callables. 

Require user might be a bit tricky here, I think we'd have to roll our own. Which might mean we end up implementing our own callable decorator rather than just wrapping anvil's. It's not out of the question though. 

Uplink wouldn't work. Not that it would currently work out the box.  you'd need to put the anvil labs source code in your uplink script.

**Comment by s-cork** [comment]
What about this as an api?

```python
with kompot.batch_call() as c:
    kompot.call(...)
    kompot.call(...)

r1, r2 = c.result
```

**Comment by hugetim** [comment]
I do like the context manager idea. Would it be `c.call(...)`, though?

I'd love to be able to write `r1 = c.call(...)` within the context manager, but I can't see how it's possible, myself.

**Comment by s-cork** [comment]
Either c.call or kompot.call could be the implementation. 

And yeah we couldn't do `r1 = c.call` since we'd only make the batched call on exiting the context.
